apiVersion: v1
kind: Service
metadata:
  name: pocex1
spec:
  selector:
    app: pocex1
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 5001
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pocex1
spec:
  selector:
    matchLabels:
      app: pocex1
  replicas: 5
  template:
    metadata:
      labels:
        app: pocex1
    spec:
      containers:
      - name: flask-test-app
        image: apiex
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5001